#dont write container nimae with integer we must fix that
containername: hostname
image: nginx
subnet: 172.17.0.1/16
replicas: 3
command :
    - sleep
    - 1200
ansiblePlaybookPath: /home/ubuntu/miniCloud/miniCloud/ansiblePlaybook.yml