# builder image
FROM golang:latest
RUN mkdir /build
ADD  .  /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/client  cli/cmd/main.go

# generate clean, final image for end users


# executable
ENTRYPOINT [ "./bin/client" ]