# builder image
FROM golang:latest
RUN mkdir /build
COPY ./cli  /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/client  /cmd/main.go

# generate clean, final image for end users


# executable
ENTRYPOINT [ "./bin/client" ]