// file: invoicer.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/Message.proto

package Message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containername       string   `protobuf:"bytes,1,opt,name=containername,proto3" json:"containername,omitempty"`
	Image               string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Subnet              string   `protobuf:"bytes,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Nunofinstance       int32    `protobuf:"varint,4,opt,name=nunofinstance,proto3" json:"nunofinstance,omitempty"`
	Command             []string `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	AnsiblePlaybookPath string   `protobuf:"bytes,6,opt,name=ansiblePlaybookPath,proto3" json:"ansiblePlaybookPath,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_proto_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetContainername() string {
	if x != nil {
		return x.Containername
	}
	return ""
}

func (x *Req) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Req) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *Req) GetNunofinstance() int32 {
	if x != nil {
		return x.Nunofinstance
	}
	return 0
}

func (x *Req) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Req) GetAnsiblePlaybookPath() string {
	if x != nil {
		return x.AnsiblePlaybookPath
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp string `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_proto_Message_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

type DReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containername string `protobuf:"bytes,1,opt,name=containername,proto3" json:"containername,omitempty"`
	Nunofinstance int32  `protobuf:"varint,2,opt,name=nunofinstance,proto3" json:"nunofinstance,omitempty"`
}

func (x *DReq) Reset() {
	*x = DReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DReq) ProtoMessage() {}

func (x *DReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DReq.ProtoReflect.Descriptor instead.
func (*DReq) Descriptor() ([]byte, []int) {
	return file_proto_Message_proto_rawDescGZIP(), []int{2}
}

func (x *DReq) GetContainername() string {
	if x != nil {
		return x.Containername
	}
	return ""
}

func (x *DReq) GetNunofinstance() int32 {
	if x != nil {
		return x.Nunofinstance
	}
	return 0
}

type WReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Containername string `protobuf:"bytes,1,opt,name=containername,proto3" json:"containername,omitempty"`
}

func (x *WReq) Reset() {
	*x = WReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WReq) ProtoMessage() {}

func (x *WReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WReq.ProtoReflect.Descriptor instead.
func (*WReq) Descriptor() ([]byte, []int) {
	return file_proto_Message_proto_rawDescGZIP(), []int{3}
}

func (x *WReq) GetContainername() string {
	if x != nil {
		return x.Containername
	}
	return ""
}

type WResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wresp string `protobuf:"bytes,1,opt,name=wresp,proto3" json:"wresp,omitempty"`
	Werr  string `protobuf:"bytes,2,opt,name=werr,proto3" json:"werr,omitempty"`
}

func (x *WResp) Reset() {
	*x = WResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WResp) ProtoMessage() {}

func (x *WResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WResp.ProtoReflect.Descriptor instead.
func (*WResp) Descriptor() ([]byte, []int) {
	return file_proto_Message_proto_rawDescGZIP(), []int{4}
}

func (x *WResp) GetWresp() string {
	if x != nil {
		return x.Wresp
	}
	return ""
}

func (x *WResp) GetWerr() string {
	if x != nil {
		return x.Werr
	}
	return ""
}

var File_proto_Message_proto protoreflect.FileDescriptor

var file_proto_Message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62,
	0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x75, 0x6e, 0x6f, 0x66, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6e, 0x6f, 0x66, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x30, 0x0a, 0x13, 0x61, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x62, 0x6f, 0x6f, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x61, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x6f, 0x6f, 0x6b, 0x50,
	0x61, 0x74, 0x68, 0x22, 0x1a, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22,
	0x52, 0x0a, 0x04, 0x44, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x6e, 0x75, 0x6e, 0x6f, 0x66, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6e, 0x6f, 0x66, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x57, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x31, 0x0a, 0x05, 0x57, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x72, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x77, 0x65, 0x72, 0x72, 0x32, 0x6b, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x76, 0x12, 0x16, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x04, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x05, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x16, 0x0a, 0x04, 0x64, 0x72, 0x6f, 0x70, 0x12, 0x05, 0x2e, 0x44,
	0x52, 0x65, 0x71, 0x1a, 0x05, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x17, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x04, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x05, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x1a, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x63, 0x68, 0x12, 0x05,
	0x2e, 0x57, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x57, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Message_proto_rawDescOnce sync.Once
	file_proto_Message_proto_rawDescData = file_proto_Message_proto_rawDesc
)

func file_proto_Message_proto_rawDescGZIP() []byte {
	file_proto_Message_proto_rawDescOnce.Do(func() {
		file_proto_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Message_proto_rawDescData)
	})
	return file_proto_Message_proto_rawDescData
}

var file_proto_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_Message_proto_goTypes = []interface{}{
	(*Req)(nil),   // 0: Req
	(*Resp)(nil),  // 1: Resp
	(*DReq)(nil),  // 2: DReq
	(*WReq)(nil),  // 3: WReq
	(*WResp)(nil), // 4: WResp
}
var file_proto_Message_proto_depIdxs = []int32{
	0, // 0: Prov.apply:input_type -> Req
	2, // 1: Prov.drop:input_type -> DReq
	0, // 2: Prov.update:input_type -> Req
	3, // 3: Prov.watch:input_type -> WReq
	1, // 4: Prov.apply:output_type -> Resp
	1, // 5: Prov.drop:output_type -> Resp
	1, // 6: Prov.update:output_type -> Resp
	4, // 7: Prov.watch:output_type -> WResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Message_proto_init() }
func file_proto_Message_proto_init() {
	if File_proto_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Message_proto_goTypes,
		DependencyIndexes: file_proto_Message_proto_depIdxs,
		MessageInfos:      file_proto_Message_proto_msgTypes,
	}.Build()
	File_proto_Message_proto = out.File
	file_proto_Message_proto_rawDesc = nil
	file_proto_Message_proto_goTypes = nil
	file_proto_Message_proto_depIdxs = nil
}
