name: Docker Image push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  BuildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy the Docker image in Docker hub
      run: docker build . --file infra/docker/Dockerfile --tag khero1234/minicloud-app && docker push khero1234/minicloud-app


     
     

   
