name: Docker Image Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  BuildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy the Docker image for Server in Docker hub
      run: docker build . --file infra/docker/Dockerfile --tag khero1234/minicloud-app &&  docker login -u khero1234 -p kherokhero && docker push khero1234/minicloud-app
    - name: Build and Deploy the Docker image for Client in Docker hub
      run: docker build . --file infra/docker/dockerfile.client --tag khero1234/minicloud-app-client &&  docker login -u khero1234 -p kherokhero && docker push khero1234/minicloud-app-client

     
     

   
